import { Inter } from "next/font/google";
import "./globals.css";
// import {font} from 'https://fonts.googleapis.com/css?family=Abel'
import Navigation from "./components/Navigation";
import Footer from "./components/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const navLinks = [
    {
      name: "Técnicas de Relaxamento",
      href: "/tecnicas-de-relaxamento",
    },
    {
      name: "Rotina Leve",
      href: "/rotina-leve",
    },
    {
      name: "Permita-se Sentir",
      href: "/permita-se-sentir",
    },
  ];
  return (
    <html lang="en">
      <body className={inter.className + " fundo"}>
        <Navigation navLinks={navLinks} />
        {children}
        <Footer/>
      </body>
    </html>
  )
}
